const HEX_BLUE_END_INDEX = 6;

const HEX_BLUE_START_INDEX = 4;

const HEX_GREEN_END_INDEX = 4;

const HEX_GREEN_START_INDEX = 2;

const HEX_PAD_LENGTH = 2;

const HEX_RADIX = 16;

const HEX_RED_END_INDEX = 2;

const HEX_RED_START_INDEX = 0;

const MAX_RGB_VALUE = 255;

export {
  HEX_BLUE_END_INDEX,
  HEX_BLUE_START_INDEX,
  HEX_GREEN_END_INDEX,
  HEX_GREEN_START_INDEX,
  HEX_PAD_LENGTH,
  HEX_RADIX,
  HEX_RED_END_INDEX,
  HEX_RED_START_INDEX,
  MAX_RGB_VALUE,
};