const INPUT_COLOR_PICKER_DEFAULT_COLOR = "#000000";

const INPUT_COLOR_PICKER_HEX_MAX_LENGTH = 6;

const INPUT_COLOR_PICKER_HEX_FILTER_REGEX = /[^0-9a-fA-F]/gu;

export {
  INPUT_COLOR_PICKER_DEFAULT_COLOR,
  INPUT_COLOR_PICKER_HEX_FILTER_REGEX,
  INPUT_COLOR_PICKER_HEX_MAX_LENGTH,
};