export default {
  cleanTempDir: "always",
  incremental: true,
  incrementalFile: "tests/mutation/incremental/incremental.json",
  tsconfigFile: "tsconfig.json",
  testRunner: "vitest",
  ignoreStatic: true,
  mutate: [
    "app/App.vue",
    "app/**/*.{ts,vue}",
    "server/**/*.ts",
    "!**/*.config.ts",
    "!**/*.constants.ts",
    "!**/*.d.ts",
    "!**/*.types.ts",
    "!**/*.spec.ts",
  ],
  plugins: [
    "@stryker-mutator/vitest-runner",
    "./configs/stryker/plugins/stryker-define-props-ignorer-plugin.mjs",
    "./configs/stryker/plugins/stryker-define-emits-ignorer-plugin.mjs",
    "./configs/stryker/plugins/stryker-define-page-meta-ignorer-plugin.mjs",
    "./configs/stryker/plugins/stryker-define-model-ignorer-plugin.mjs",
    "./configs/stryker/plugins/stryker-define-expose-ignorer-plugin.mjs",
  ],
  ignorers: [
    "defineProps",
    "defineEmits",
    "definePageMeta",
    "defineModel",
    "defineExpose",
  ],
  ignorePatterns: [
    "!.nuxt/",
    ".github/",
    ".husky/",
    ".output",
    ".opencode",
    ".run/",
    ".idea/",
    "dist",
    "configs/commitlint",
    "configs/cucumber",
    "configs/eslint",
    "configs/lint-staged",
    "configs/stryker",
    "configs/node",
    "tests/acceptance",
    "tests/mutation",
    "tests/unit/coverage",
    "scripts/",
    ".editorconfig",
    ".npmrc",
    ".nvmrc",
    "release.config.mjs",
    ".DS_Store",
    ".validate-branch-namerc.json",
    "CHANGELOG.md",
    "LICENSE",
    "pnpm-lock.yaml",
    "sonar-project.properties",
    "README.md",
    ".coderabbit.yaml",
  ],
  vitest: { configFile: "configs/vitest/vitest.config.ts" },
  reporters: ["clear-text", "progress", "html", "json"],
  htmlReporter: { fileName: "tests/mutation/coverage/index.html" },
  jsonReporter: { fileName: "tests/mutation/coverage/mutation.json" },
  thresholds: {
    high: 100,
    low: 100,
    break: 100,
  },
  dryRunTimeoutMinutes: 10,
  disableTypeChecks: false,
};