const HEX_COLOR_DARKEN_AMOUNT = 0.2;

const HEX_COLOR_DEFAULT_NEUTRAL = "#6b7280";

const HEX_COLOR_LIGHTEN_AMOUNT = 0.2;

export {
  HEX_COLOR_DARKEN_AMOUNT,
  HEX_COLOR_DEFAULT_NEUTRAL,
  HEX_COLOR_LIGHTEN_AMOUNT,
};