const BEFORE_ALL_TIMEOUT = 360_000;

const BEFORE_TIMEOUT = 10_000;

const ACCEPTANCE_TESTS_DEFAULT_LOCALE = "en";

export {
  ACCEPTANCE_TESTS_DEFAULT_LOCALE,
  BEFORE_ALL_TIMEOUT,
  BEFORE_TIMEOUT,
};