const BEFORE_ALL_TIMEOUT = 360_000;

const BEFORE_TIMEOUT = 10_000;

const ACCEPTANCE_TESTS_DEFAULT_LOCALE = "en";

const SANDBOX_BASE_URL = "http://localhost:9090";

const SANDBOX_ADMIN_KEY = "test_admin_api_key_for_testing";

const SANDBOX_HEALTH_CHECK_URL = `${SANDBOX_BASE_URL}/health`;

const SANDBOX_HEALTH_CHECK_MAX_RETRIES = 10;

const SANDBOX_HEALTH_CHECK_INTERVAL_IN_MS = 2000;

export {
  ACCEPTANCE_TESTS_DEFAULT_LOCALE,
  BEFORE_ALL_TIMEOUT,
  BEFORE_TIMEOUT,
  SANDBOX_ADMIN_KEY,
  SANDBOX_BASE_URL,
  SANDBOX_HEALTH_CHECK_INTERVAL_IN_MS,
  SANDBOX_HEALTH_CHECK_MAX_RETRIES,
  SANDBOX_HEALTH_CHECK_URL,
};